#!/bin/bash
### BEGIN INIT INFO
# Provides: gophish
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: stops/starts gophish application server
### END INIT INFO


# define scripts variables

processName=Gophish
process=gophish
appDirectory=/home/user
logfile=/var/log/gophish/gophish.log
errfile=/var/log/gophish/gophish.error

start(){
echo 'Starting my '${processName}'...'
cd ${appDirectory}
nohup ./$process>>$logfile 2>>$errfile &
sleep 1
}

stop(){
echo 'Stopping my '${processName}'...'
pid=$(/usr/bin/pidof ${process})
kill ${pid}
sleep 1
}

status(){
pid=$(/usr/bin/pidof ${process})
if [["$pid"!=""]]; then
	echo ${processName}' is running...'
else
	echo ${processName}' is not running...'
fi
}

case "$1" in
start|stop|status) "$1";;
esac
